language: python
python:
  - "2.7"
env:
  - KOTTI_TEST_DB_STRING=postgresql://postgres@localhost:5432/kotti_alert_testing
  - KOTTI_TEST_DB_STRING=sqlite://
install:
  - pip install "pip==1.3.1"  # fix issue with fanstatic==1.0a
  - pip install psycopg2 oursql
  - pip install -e . -r https://raw.github.com/Kotti/Kotti/stable/requirements.txt
  - pip install "wsgi_intercept==0.5.1"
  - python setup.py dev
  - psql -c 'create database kotti_alert_testing;' -U postgres
script: py.test --tb=native --cov=kotti --cov-report=term-missing
